### ISSUE TITLE
Migration during Install fails

### ISSUE THREAD

**Issue by TravisWilder** [DirectoryTree/Scout#12]
Hello,
during install the migration is failing (also via cli)

`Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'ldap_updated_at' (SQL: create table `ldap_scan_entries` (`id` bigint unsigned not null auto_increment primary key, `scan_id` bigint unsigned not null, `parent_id` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null, `ldap_updated_at` timestamp not null, `guid` varchar(255) not null, `name` varchar(255) not null, `dn` varchar(255) not null, `type` varchar(255) null, `values` longtext null, `processed` tinyint(1) not null default '0') default character set utf8mb4 collate 'utf8mb4_unicode_ci')`

With 

 $table->timestamp('ldap_updated_at')->nullable();

it worked

**Comment by stevebauman** [comment]
Hi @TravisWilder, thanks for your interest in Scout! Appreciate the report :smile:

I've just fixed this.
